// <auto-generated />
namespace ReadingApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class BookDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202001240126028_BookDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
